### ISSUE TITLE
On including bundles in the repo

### ISSUE THREAD

**Issue by stroborobo** [Bixie/pagekit-framework#6]
Hey Matthijs,

I'm getting more and more annoyed that the bundles are included in the repo. Everytime I run a build those files are changed slightly [for no other reason than a different path on different systems](https://github.com/Bixie/pagekit-framework/blob/a33ecb9/app/bundle/fieldtype-email.js#L57). After the build I always need to `git checkout` some files and clean up our submodule, so it's not flagged as '-dirty'.

Source code need to be built and you don't put binaries into a repo of a C based project, so why do this in Javascript?

What's your thoughts about this?

**Comment by malles** [comment]
I'm annoyed as well :) Fortunately I don't pull as much as I push, but you are right. The build files should not be in the repo.
That being said, the Pagekit Marketplace auto-updater fetches the code from Github automatically. That is the reason why the bundle files are in the repo.
Alternatively I would have to build release packages and update the Marketplace manually that way. I am thinking of doing that, I'll ask the Pagekit devs if there is another better solution.

**Comment by stroborobo** [comment]
It really gets the code, not the releases? That's odd.

Thank you for considering that change. :)

**Comment by malles** [comment]
No more whining, just did it :) Glad to be rid of them.

**Comment by stroborobo** [comment]
Great, thanks!
